# Generated by Django 5.0.3 on 2024-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL TIME ', 'FULL TIME'), ('PART TIME ', 'PART TIME ')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
