# Generated by Django 5.0.3 on 2024-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discraption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
