# Generated by Django 5.0.3 on 2024-04-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_experience_job_puplish_at_job_salary_job_vacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
