# Generated by Django 5.0.3 on 2024-04-04 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_catagorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Catagroy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.catagorys'),
            preserve_default=False,
        ),
    ]
